### ISSUE TITLE
Copy/paste error leads to bad macro?

### ISSUE THREAD

**Issue by aghast** [phao/XError#1]
https://github.com/phao/XError/blob/d2bb5239c48401b4a3d84d489239410dac518cc3/XError.h#L123

I suspect the macro has the wrong parameters, and the expansion is actually correct.

**Comment by phao** [comment]
You are completely right.

But, man... it has been so long since I last looked these things.

I believe the right macro definition should be:

`#define PErrIf0(COND, VAL) ErrIf0(COND, VAL, 0)`
